### ISSUE TITLE
Exception continueException in getitem

### ISSUE THREAD

**Issue by Echo0125** [songdejia/EAST-AutoTrainEval-pytorch#39]
After the pre-trained, I want to train the model on my own datasets, and I prepared my training set according to the requirements in the README. But when I run the run.py , problems occured:
EAST <==> Prepare <==> Network <==> Done
Exception continue
Exception in getitem, and choose another index:133
Exception continue

So how could I solve this problem？ Thank you.

**Comment by jinzhiyang1** [comment]
您好，祝您新年快乐。我也遇到相同的问题了，请问您解决这个问题了么，如果解决了，可以分享一下经验吗？
